### PR TITLE
Add simple type identity overload for injectable

### PR DESCRIPTION
**Pull request by albertogasparin**
Make type infer faster and prevent some issues with partial of circular types by providing a plain identity overload
Thanks @theKashey

### CODE REVIEW

**Comment by theKashey** [comment]
😄

**Comment by theKashey** [comment]
Types might be not very correct. The definition order of overloading function matters and TS will use the first matched one.
I failed to create any local test for that, but on a real project the _reverse_ order of definition generates less strange errors.

Example of the error 
```tsx
injectable((props: PropsWithChildren) => null, ({children}) => null);
// children will be required on the right and optional on the left. 
// TS Error, you are dead
```

**Comment by albertogasparin** [comment]
Right, but if we put identity later wouldn't the circular types make TS blow up anyway?

**Comment by theKashey** [comment]
Playing with it...
- splitting into 3 types - component, match, deepEqual is not working
- component, deepEqual match... is not working
- match, componentOrFunction requires a little massaging for some mocks
- componentOrFunction, match works most of the times

**Pull request merged**
