### PR TITLE
make parametrs also optional

### PR DESCRIPTION
**Pull request by pawk3k**
I have added a small tweak on types, what do you think about making parameters for functions also optional :). Feel free to reject this Pr if it was intentional to make parameters required for injected things

### CODE REVIEW

**Comment by theKashey** [comment]
Arguments are DeepPartial in any case, up to being omitted at all.

The only known _gap_ in DeepPartial is not handling Promises - they are still expected to be specified in full, if specified at all.

**Comment by pawk3k** [comment]
Yes but i'm saying about a case for 
```ts
type Obj = {
fun: (param1:string,param2:string) // this to become optional
}
```

**Comment by theKashey** [comment]
It is optional as TypeScript does a structural comparison and in this case "smaller" is assignable to "bigger" - https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwIxQLxQN4CgBmBXAOwC4oAKMAQwCcKBbJIgZ2CoEsCBzAGkptoCYmLdhwCUqAHwA3APasAJlAD0SqMAAWrRmplQ4EAMYza0GWGCsZBCgBssAXyxGCzNRGYl4yNJixR8xGTiEphUEMB4VARQAOQAHnExjvZAA
```
type Obj1 = {
fun: (param1:string,param2:string)=>void // this to become optional
}
const test: Obj1 = {
fun: ()=> {}
}
```

**Comment by pawk3k** [comment]
Technically yes but  you can't call it without arguments https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwIxQLxQN4CgBmBXAOwC4oAKMAQwCcKBbJIgZ2CoEsCBzAGkptoCYmLdhwCUqAHwA3APasAJlAD0SqMAAWrRmplQ4EAMYza0GWGCsZBCgBssAXyxGCzNRGYl4yNJixR8xGTiEphUEMB4VARQAOQAHnExjo5YWMDuwAB0AaSiQA

**Comment by theKashey** [comment]
https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwIxQLxQN4CgBmBXAOwC4oAKMAQwCcKBbJIgZ2CoEsCBzAGkptoCYmLdhwCUqAHwA3APasAJlAD0SqMAAWrRmplQ4EAMYza0GWGCsZBCgBssAXyxGCzNRFfpsUfMTLiJmFQQwHhUBFAA5AAeURGO9lCMFBaMOKzusIhIANxYecDuwAB0PqSiQA
```tsx
const test = {
 fun: ()=> {return 'xx'}
} satisfies Obj1;
```

But you are not the one calling this function, it's expected to be injected into the one calling it.

----

So let's start from scratch - why you need this change? Where this started, show me the use case.

**Comment by pawk3k** [comment]
Sorry for the delay I just realized that I wanted to use a deep part of the magnetic-di outside of the context of magnetic di. I believe then this pr should be closed, thanks for your participation.

**Pull request closed without merging**
